version: '3.8'

services:
  qvcache:
    container_name: qvcache
    image: qvcache:latest
    build: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: bash
    stdin_open: true
    tty: true
